opengsn/gsn

- contracts/SampleRecipient.sol
- package.json
- test/clientlib.js
- test/relay_contract.js
- test/testutils.js
1. Add 'set_blacklisted' method to Sample Recepient instead of hardcoded
2. Create 'register_new_relay_with_privkey' to be used for relay
penalize tests. This test requires signing two transactions with the
same nonce, which AFAIK cannot be done with Web3 and requires access to
private key. Therefore, 'register_relay' transaction has to be signed by
this key instead of by Web3 account.
> Allow tests to pass without deterministic mode in Ganache

- contracts/RelayRecipient.sol
- contracts/RelayRecipientApi.sol
- contracts/SampleRecipient.sol
- src/js/relayclient/RelayRecipientApi.js
- src/js/relayclient/relayclient.js
- src/js/webtools/contractmanager.js
- src/js/webtools/relaymanager.js
- src/js/webtools/utils.js
- test/flows.js
- added get_recipient_balance() to check balance (and also validate the
existence of the hub)
- call it from `set_relay_hub_internal()`
- make `relay_hub` member private (to require setter and getter)
- added `get_relay_hub()` to return it as RelayHub, and separate
`get_hub_addr()`, which is used from RelayRecipientApi
> Refactor RelayRecipient - get_recipient_balance, etc

- package.json
- src/js/relayclient/RelayProvider.js
On Ropsten, app floods with getTransactionReciept() (anywhere between 50 to 4000 times, while waiting for transaction to be mined)
> Bugfix flood tx

- package.json
For projects that install 'tabookey-gasless' as a dependency, use this command to run web tools instead of cloning entire repository:
npm explore tabookey-gasless -- npm run webtools
> Add 'webtools.webpack.js' to package to run webtools without clone

- server/src/librelay/relay_server.go
- server/src/librelay/relay_server_test.go
- src/js/relayclient/relayclient.js
- test/clientlib.js
It is possible for a relay to delay the relayed transaction indefinitely
by giving it a very high nonce.
The client's responsibility is then to decide (wisely) what is the
maximum relay nonce he will accept.
Higher nonce tx is be considered invalid. The client keeps trying other
relays. That is expected to trigger a race between the discarded high
nonce transaction and another one, with only one of them able to make it
to the blockchain.
On the server side, getting a 'RelayMaxNonce' lower than known
'lastNonce' leads to immediate error.
> GLS-49 Add 'RelayMaxNonce' to relay request

- contracts/RelayHub.sol
- contracts/TestRecipientUtils.sol
- test/relay_contract.js
There is no legitimate reason for a relay address to be controlled by a
smart contract within our design of Relay Network.
Making sure that message sender is the transaction origin is the safest
way to validate the caller is externally-owned.
> GLS-50 In RelayHub, verify that relays are not contracts

- src/js/relayclient/relayclient.js
Client calculates gas price based on accepted txfee.
however, it must send this value always as integer to the server.
> client must send gas price as integer

- package-lock.json
- package.json
- src/js/relayclient/HttpWrapper.js
- src/js/relayclient/RelayClient.js
- test/http_wrapper_test.js
- test/server_helper_test.js
- test/testutils.js
Adds a configurable timeout to all http requests done via the HTTP wrapper. 
Uses [axios](https://www.npmjs.com/package/axios) to manage http requests, instead of the web3 http provider, which has a configurable http timeout out of the box. The value is configurable, and set to 10 seconds by default in the RelayClient.
Fixes #73.
> HTTP timeout

- src/js/relayclient/RelayClient.js
- src/js/relayclient/ServerHelper.js
- test/server_helper_test.js
Adds options to the relay client to specify custom functions to filter and sort relays when listing them from the relay hub. Defaults to filtering by stake and delay (if specified) and filtering by transaction fee.
This PR also fixes the existing sorting by transaction fee, which was using a non-existing `txFee` field instead of `transactionFee`, and uses bignumber for all comparisons (since web3 beta.37 returns all numeric values as strings).
Fixes #79.
> Relay client strategy for fetching relays

- src/js/relayclient/utils.js
- test/relay_hub_test.js
ethereumjs-tx returns tx signature fields v,r,s as buffers, and
truncates them if they have leading zeroes, which is a problem when
doing ecrecover on-chain.
> Fixing flickering test

- contracts/RelayHub.sol
- contracts/RelayHubApi.sol
- contracts/RelayRecipient.sol
- contracts/RelayRecipientApi.sol
- contracts/SampleRecipient.sol
- package-lock.json
- package.json
- scripts/singleton/compute.sh
- scripts/singleton/get-deploy-data.js
Fixes https://github.com/tabookey/tabookey-gasless/issues/93
This adds scripts in `scripts/singleton`, which generate a single contract using [truffle-flattener](https://github.com/nomiclabs/truffle-flattener), compile it, craft a transaction with a synthetic signature (0x1613161316131613...) that deploys it, and output the contract's source code, ABI, and deployment details (the transaction itself, the address that must be funded in order to execute the transaction, and the contract address).
I originally made the script generate a vanity address (e.g. one that starts with 0x1613), but that adds quite a bit of complexity, takes a long while to compute, and feels like a gimmick overall: it creates false confidence in an address that starts with that prefix, when a) it's very easy to …
> RelayHub singleton

- .gitignore
- package-lock.json
- package.json
- scripts/fundrelay.js
- scripts/ganache-fund.js
- scripts/run-ganache
- server/Makefile
- server/scripts/test.sh
- server/src/RelayHttpServer.go
- server/src/librelay/relay_server.go
- server/src/librelay/relay_server_test.go
- server/src/librelay/test/utils.go
- server/src/librelay/tx_store.go
- server/src/librelay/txstore/leveldb_store.go
- server/src/librelay/txstore/memory_store.go
- server/src/librelay/txstore/tx_store.go
- server/src/librelay/txstore/tx_store_test.go
Adds a new `TxStore` component that stores all unconfirmed transactions, with two implementations: an in-memory one and a LevelDB-backed one. Transactions are stored ordered by increasing nonce. Whenever a transactions is sent, it is added to the store.
RelayServer has now a `UpdateUnconfirmedTransactions` method for updating the transactions on the store. This process removes all transactions from the store that have been confirmed (ie mined at least 12 blocks ago). If the transaction with the lowest nonce is pending (ie not mined) after 5 minutes, it is resent with an increased gas price (25% extra, with a max cap), and its timestamp is reset.
This method is now invoked every minute from the RelayHTTPServer.
Fixes #77
> Store pending transactions in relay

- contracts/GsnUtils.sol
- contracts/IRelayHub.sol
- contracts/IRelayRecipient.sol
- contracts/Migrations.sol
- contracts/RLPReader.sol
- contracts/RelayHub.sol
- contracts/RelayRecipient.sol
- contracts/SampleRecipient.sol
- contracts/TestRecipientUtils.sol
- samples/contracts/KnownUsersRecipient.sol
- samples/contracts/TokenRecipient.sol
- test/relay_hub_test.js
following Zepelin's audit added some fixes.
fixed pragma solidity
removed abstract methods from RelayRecipient (as they duplicate IRelayRecipient's)
added documentation of main methods.
cleaned up comments
removed initRelayHub() - to signify setRelayHub should be used (and support updated relay)
> Fixes on audit comments.

- .circleci/config.yml
- .gitignore
- README.md
- coverage-prov.js
- coverage.html
- package-lock.json
- package.json
- scripts/run-coverage
- scripts/run-coverage-if-changed.sh
- test/flows_test.js
- test/relay_hub_test.js
- truffle.js
add code-coverage for the RelayHub.
Currently the code coverage stands on 97%
The coverage is done during unittest `relay_hub_test.js`.
For the integration tests (with a real relay), we must use external ganache, which breaks the coverage test.
> Add Code Coverage for contract

- contracts/SampleRecipient.sol
- test/relay_hub_test.js
This proved to be a special case for some solidity precompiles (it breaks the abi.decode, for instance).
This will prevent similar bugs in the future.
> Add test for a relayed method with no parameters

- .circleci/config.yml
- contracts/RelayHub.sol
- coverage-prov.js
- dock/Dockerfile
- truffle.js
This upgrades the compiler version to use v0.5.10, which includes a fix for https://github.com/ethereum/solidity/issues/6901, letting us remove `staticCallWithMaxGas` and its inline assembly.
> Upgrade to solc-0.5.10

- contracts/RLPReader.sol
- migrations/2_deploy_contracts.js
This changes `RLPReader` so that it is no longer an external library (that needs to be linked), but an internal one that is inlined. This is necessary in order to achieve #93.
> Internal libraries

- contracts/IRelayHub.sol
- contracts/RelayHub.sol
- contracts/SampleRecipient.sol
- test/RelayHub.test.js
This PR adds a check to assert that `acceptRelayedCall` doesn't return a reserved error code, and emits a new code when this happens.
> Invalid error codes in acceptRelayedCall

- src/js/relayclient/RelayClient.js
Instead of just accepting tx fee when initializing the relay provider, support specifying the txfee parameter along with from, gas, to, gasPrice, etc in each tx. Also defaults fee to 12, which is above the relayer default minFee of 11.
> Support setting txfee in tx options and add default value

- dock/Dockerfile
- dock/killdock.sh
- restart-relay.sh
- scripts/fundrelay.js
fixes #162 and #163 
1. Installed `truffle` and `ganache-cli` as a global package for docker
2. Optimize dependencies installation for docker i.e. removed redundant `apt-get update` commands 
3. Updated `killdock.sh` script 
4. updated unstakeDelay value in `fundrelay` script.
> Fix relaydocker

- server/Makefile
- server/scripts/get_abi_bin.js
Changing out directory of bin,abi files from build/contracts to
build/server/contracts since truffle doesn't like having non json files
in there.
> Fix Makefile

- build_server_docker.sh
- package.json
- scripts/gsn-dock-relay
- serverdock/Dockerfile
- serverdock/truffle.js
- yarn.lock
update the `npm run gsn-dock-relay-ganache` command
also tagged the npm package as 0.4.0-beta1
> Publish 0.4 docker relay 

- server/src/RelayHttpServer.go
Set the default rhub address in the relayer process to match the singleton deployment address.
> Fix default rhub address in relayer

- contracts/IRelayHub.sol
- contracts/RelayHub.sol
- contracts/SampleRecipient.sol
- test/RelayHub.test.js
If a recipient wants to withdraw funds from the rhub, the contract itself needs to call the `withdraw` function on the hub, which transfers funds to the contract. This forces the contract to implement a fallback payable function (ie to accept funds) in order to receive that transfer. Adding a fallback payable function is generally not a good idea, unless there is a mechanism in place to process arbitrary payments made to the contract.
To fix this, we can add a `dest` parameter to rhub's `withdraw`, which indicates who actually receives the withdrawn funds. This removes the requirement for any recipient to have to accept (and manage) funds from any source. Old behaviour can be preserved by just specifying the contract's own address as `dest`.
We considered the alternative of adding a …
> Add destination parameter to rhub withdraw

- prodserverdock/relay/config/relay.txt
- server/src/RelayHttpServer.go
- server/src/librelay/relay_server.go
- server/src/librelay/relay_server_test.go
- test/testutils.js
Adds a new bool flag -DevMode (defaults to false). When set, the relayer does not cache its account nonce, and does not try resending unconfirmed txs. This is useful when running unit tests against a relayer instance using ganache: if the test suite rollbacks the blockchain state on each test, the relayer account nonce falls out of sync. This mode prevents this, and allows having a long-running relayer for the whole test suite.
> Add dev mode to relayer server

- server/src/RelayHttpServer.go
- server/src/utils.go
This PR increases the short sleep interval from 100ms to 1s. When running the relayer on a CI in a large test suite (such as openzeppelin contracts), the short sleep stressed the CI and caused the entire job to timeout. Increasing the short sleep interval fixed this, by reducing the pressure on the CI runner.
Links to the relevant CI runs:
- [Without relayer](https://travis-ci.com/OpenZeppelin/openzeppelin-contracts/builds/121313660): runs in 12 min
- [With relayer on 100ms](https://travis-ci.com/OpenZeppelin/openzeppelin-contracts/builds/121809414): timeouts at 50min
- [With relayer on 1s](https://travis-ci.com/OpenZeppelin/openzeppelin-contracts/builds/121817387): runs in 28min
Note that this change does not affect this repository's test time. I run `time npm test` on this repository on …
> Increase short sleep interval tenfold

- server/src/RelayHttpServer.go
- server/src/librelay/relay_server.go
Maximum value for uint64 is about 18e18. If the relayer has more than those funds, the comparison against minRelayBalance will fail, and the relayer will not start due believing it has not enough balance.
> Do not cast relayer balance to uint64

- server/src/relay/RelayHttpServer.go
The current default workdir is `build/server`, which is useful for development within this project, but is odd for an end user running the relayer locally. This PR changes the default to `data`.
> Default relayer workdir to data

- server/src/librelay/relay_server.go
- server/src/librelay/relay_server_test.go
- server/src/relay/RelayHttpServer.go
- test/relay_client_test.js
- test/relay_hub_test.js
Since the on-chain calculation is too tight. It seeems as if the size of the encodedFunction might be responsible for this, So I added a calculation per the yellowpaper for its gas cost and added it to the relayed tx's gas limit.
Also removed duplicate line in test removed unused params
> Added some slack to required gas of relayed call

- contracts/SampleRecipient.sol
- src/js/relayclient/RelayClient.js
- test/relay_client_test.js
The client should check if the transaction it generates is valid
on-chain, before sending it to a relay.
This is done by calling the same `RelayHub.canRelay()` method used by
the relay itself to check the transaction validity.
Without this check, in case the transaction would fail, the relay would
reject it. But in this case, the client would continue to try and send
the transaction through all relays, instead of stopping after first
failure.
When signing a transaction with Metamask, this also has the side-effect
of requiring the user to confirm signing the transaction again for each
such relay access attempt.
> RelayClient: should check if "canRelay()" before calling a relay.

- .gitignore
- build_server_docker.sh
- package.json
- publish_server_docker.sh
- scripts/gsn-dock-relay
- serverdock/Dockerfile
- serverdock/start-relay.sh
Test relay docker image (used by `npx gns-dock-relay-ganache`) should use the same
public RelayHub address used in all production networks.
> Local dock relay should use public relay address

- server/src/relay/RelayHttpServer.go
This updates the default RelayHub address to the canonical one: [0xD216153c06E857cD7f72665E0aF1d7D82172F494](https://etherscan.io/address/0xD216153c06E857cD7f72665E0aF1d7D82172F494#code)
> Update default RelayHub address

- package.json
Background:
I'm using this library for my project (Burner Wallet 2), and I'm trying to reduce the size of the compiled bundle of the app. The largest cause of bundle inflation is coming from us bundling many different versions of web3, since different libraries all have different dependencies.
-----
This PR updates web3 to version 1.2, which is the LTS version. It also updates abi-decoder to bring its web3 version inline. `bignumber.js` is no longer bundled in with web3, so it is added to the devDependencies so the tests will pass.
> Update web3 to 1.2.x

- src/js/relayclient/RelayProvider.js
In case RelayProvider is configured against previous RelayProvider, it
should bypass the old one, and use its "orig-provider" directly.
> RelayProvider double-initialization doesn't work.

- .eslintrc.js
- contracts/SampleRecipient.sol
- src/js/relayclient/RelayClient.js
- src/js/relayclient/RelayProvider.js
- test/flows_test.js
add missing transaction options:
- useGSN - set to `false` to bypass the GSN network for this specific transaction.
- approvalData - set the `approvalData` value of the transaction. This value can be checked by the `RelayRecipient` to verify the call (e.g. some sort of signature over tx content, sender, etc)
> add useGSN, approvalData options

- src/js/relayclient/RelayClient.js
This is to allow a) testing the relay client without depending on the
relay process (as opposed to current approach of running actual relay in
a docker) and b) will eventually allow other channels of talking to
relays other then HTTP (name should be changed then)
> Allow use of injected HttpWrapper throughout the RelayClient

- contracts/RelayHub.sol
- server/src/librelay/relay_server.go
- server/src/librelay/relay_server_test.go
- server/src/relay/RelayHttpServer.go
- src/js/relayclient/RelayClient.js
- src/js/relayclient/ServerHelper.js
- src/js/relayclient/utils.js
- test/SampleRecipient.test.js
- test/server_helper_test.js
Don't require relays to re-register. once is enough.
- look for all relay events (not only RelayAdded) in the past X blocks (~30 days)
- after finding unique relays, look up for latest RelayAdded for each one of them.
- client can specify `preferredRelays` (urls)
- these relays are always added at the beginning of the relays list (only checked for "ping", not txfee/stake/delay)
- only if none of the preferred relays answer, it will continue with the rest of the "public" relays
> Lower-cost relays

- contracts/BaseGsnAware.sol
- contracts/BasePaymaster.sol
- contracts/BaseRelayRecipient.sol
Paymaster and RelayRecipient are different entities, each knows about a
RelayHub.
But if a single entity has to inherit them both, it must still have a
single relayHub for both purposes.
Without this base class, there are two members named `relayHub`, and its
very confusing as to which one is in use.
So we add a base contract named `BaseGsnAware` which only has the
`relayHub` member for that purpose.
> Add BaseGsnAware baseclass

- .gitignore
- contracts/BaseRelayRecipient.sol
- contracts/RelayHub.sol
- contracts/TrustedForwarder.sol
- contracts/interfaces/IRelayHub.sol
- contracts/interfaces/ITrustedForwarder.sol
- contracts/test/TestProxy.sol
- contracts/test/TestRecipient.sol
- contracts/utils/GsnUtils.sol
- migrations/2_deploy_contracts.js
- package.json
- server/src/librelay/relay_server_test.go
- src/js/relayclient/EIP712/Eip712Helper.js
- src/js/relayclient/RelayClient.js
- src/js/relayclient/utils.js
- src/js/relayserver/RelayServer.js
- test/RelayHub.test.ts
- test/RelayHubGasCalculations.test.ts
- test/RelayHubPenalizations.test.js
- test/RelayHubStakeManagement.test.js
- test/TokenPaymaster.test.js
- test/Utils.test.js
- test/flows_test.js
- test/relay_client_test.js
TrustedForwarder contract
- client recipient has a reference to its trusted forwarder (NOT relayhub)
- probably can be set at the constructor -  less likely to change (still, it might change - e.g. if signature struct changes)
- holds all functionality of nonce, signature verification.
> TrustedForwarder contract

- src/common/utils.js
- src/relayserver/KeyManager.js
- test/KeyManager.test.js
- test/RelayHubPenalizations.test.ts
Blast from the past: https://github.com/ethereumjs/ethereumjs-vm/issues/710
Alex and I already discussed this issue and commented on their open issue in their repo, which still exists.
> Flickering test fix

- .circleci/config.yml
coverage is currently broken: it doesn't recognize all contracts.
Until it is fixed, it is disabled.
> disable coverage in circleCI

- .circleci/config.yml
- .gitignore
- buidler.config.js
- migrations/2_deploy_contracts.js
- src/relayclient/DevRelayClient.ts
- src/relayclient/RelayedTransactionValidator.ts
- src/relayserver/HttpServer.js
- src/relayserver/KeyManager.js
- src/relayserver/RelayServer.js
- src/relayserver/TxStoreManager.js
- src/relayserver/runServer.js
- test/KeyManager.test.js
- test/RelayServer.test.js
- test/TestUtils.ts
- test/TxStoreManager.test.js
- RelayServer separation of manager from worker (initial support for multiple workers, though only 1 is currently implemented)
- added support for hdkeys in KeyManager
- TxStorage now support unique **(nonce,signer)**
other changes:
- better handling of startup errors
- handling of intermediate states (waiting for fund/register) not as errors
- TxStorage, KeyManager now support in-memory state
> RelayServer separate worker and manager

- contracts/BaseRelayRecipient.sol
- test/regressions/PayableWithEmit.sol
- test/regressions/PayableWithEmit.test.ts
getSender() does SLOAD (to get the Forwarder), and thus (after istanbul
fork) is much more expensive than msg.sender.
If used from the default payable function, it might cause the payable to
revert.
The fix: make sure not to read storage in case the msg.data is shorter,
thus getSender() becomes much less expensive.
> Fix payable default function with getSender()

- README.md
- contracts/BaseRelayRecipient.sol
- contracts/interfaces/IRelayRecipient.sol
- contracts/test/TestProxy.sol
- contracts/test/TestRecipient.sol
- test/regressions/PayableWithEmit.sol
- test/regressions/PayableWithEmit.test.ts
This will reduce changes to OpenZeppelin - based subclasses. Note that some changes are still required, bacause:
- sender is  no longer depends on relayHub, but on trustedForwarder
- payments works differently (by separate paymaster, not by each recipient)
> Rename getSender to _msgSender

- contracts/BasePaymaster.sol
- test/SampleRecipient.test.js
add default payable function to paymaster.
This makes it much easier to replenish it: simply by transfering eth,
without the caller knowing that `RelayHub.depositFor(paymaster)` is
required
(RelayHub has a protection to prevent a deposit of more than 2 eth, which is applied to this transfer too)
NOTES:
Behaviour should be documented since:
- Checking the ***balance*** of the paymaster will always show "zero", even
after eth is transfered into it.
- By default, a paymaster has no way to withdraw its own deposit: You
must inherit it, and add a method that uses the `relayhub.withdraw` (which only the paymaster
itself can call)
> Paymaster is payable

- package.json
- scripts/postpack
- scripts/prepublish
- src/cli/commands/gsn-deploy.ts
- src/cli/commands/gsn-start.ts
- src/cli/commands/gsn.ts
- src/cli/utils.ts
- src/relayclient/GsnTestEnvironment.ts
- src/relayserver/RelayServer.js
1.  export GsnTestEnvironment. can be used as
```javascript
env = require( '@opengsn/gsn/dist/GsnTestEnvironment').default
env.startGsn('local')
```
2. now report an error on null, unknown network or non-url
> startGsn cleanup

- contracts/RelayHub.sol
- contracts/forwarder/Eip712Forwarder.sol
- contracts/forwarder/IForwarder.sol
- contracts/forwarder/test/TestEip712Forwarder.sol
- contracts/forwarder/test/TestForwarderTarget.sol
- contracts/test/TestRecipient.sol
- contracts/utils/GsnEip712Library.sol
- src/common/EIP712/ForwardRequest.ts
- src/common/EIP712/TypedRequestData.ts
- src/relayclient/RelayClient.ts
- src/relayclient/RelayedTransactionValidator.ts
- src/relayserver/RelayServer.ts
- test/Eip712Forwarder.test.ts
- test/RelayHub.test.ts
- test/RelayHubGasCalculations.test.ts
- test/RelayHubPenalizations.test.ts
- test/TestBatchForwarder.test.ts
- test/Utils.test.ts
- test/relayclient/AccountManager.test.ts
- test/relayclient/RelayClient.test.ts
- test/relayclient/RelayProvider.test.ts
forwarder now has a "value" parameter, which is the amount of ether to
send with the transaction.
The {{execute()}} function is now payable, to be able to receive
this value.
Note that it is possible to pass the value into the forwarder in a call
just before execute (still, under the same transaction)
The {{execute}} would fail the request if it is given a value
parameter, but doesn't have enough value to fulfill it.
> Forwarder supports "value"

- contracts/BasePaymaster.sol
- contracts/BaseRelayRecipient.sol
- contracts/BatchForwarder.sol
- contracts/RelayHub.sol
- contracts/interfaces/GsnTypes.sol
- contracts/interfaces/IRelayHub.sol
- contracts/utils/GsnUtils.sol
- migrations/2_deploy_contracts.js
- src/cli/CommandsLogic.ts
- src/cli/StatusLogic.ts
- src/common/Constants.ts
- src/common/Environments.ts
- src/common/Utils.ts
- src/relayclient/ContractInteractor.ts
- src/relayclient/GSNConfigurator.ts
- src/relayclient/RelayClient.ts
- src/relayserver/RelayServer.ts
- test/Flows.test.ts
- test/RelayHub.test.ts
- test/RelayHubGasCalculations.test.ts
- test/RelayHubPenalizations.test.ts
- test/RelayHubRegistrationsManagement.test.ts
- test/RelayServer.test.ts
- test/SampleRecipient.test.ts
- test/TestBatchForwarder.test.ts
- test/relayclient/AccountManager.test.ts
- test/relayclient/KnownRelaysManager.test.ts
- test/relayclient/RelayClient.test.ts
- test/relayclient/RelayProvider.test.ts
- test/relayclient/RelaySelectionManager.test.ts
It makes sense that these will be different across different chains.
Will be problematic if we will need code change in order to change them.
Extra changes:
- remove 'domainSeparator' from base paymaster storage
- remove 'trustedForwarderOnly' modifier from base recipient
- remove unused code from GsnUtils
- finally fix typo ('intialized' instead of 'initialized')
> OG-124 Make all RelayHub constants constructor parameters

- patches/truffle+5.1.26.patch
truffle to save "json-input.json" file used for compilation.
This file simplifies etherscan verify.
> OG-129: Patch truffle to simplify Etherscan Verify Source

- package.json
- src/relayclient/ContractInteractor.ts
We had a hard-coded 10 million gas as a limit for the view-only call.
The issue arises when using a library on a network with block gas limit
lower then that.
> Fix external gas limit bug

- contracts/interfaces/IPaymaster.sol
Fix typos in comments referencing the incorrect return name.
> Fix typo referencing rejectOnRecipientRevert

- contracts/BasePaymaster.sol
- contracts/BaseRelayRecipient.sol
like all other contract member fields.
> trustedForwrader member should be public

- src/relayserver/RelayServer.ts
- src/relayserver/TransactionManager.ts
- test/relayserver/RegistrationManager.test.ts
- test/relayserver/RelayServer.test.ts
- test/relayserver/TransactionManager.test.ts
Also:
1. Replace BlockHeader with BlockNumber as we are not really interested
in the rest of it.
2. Add chack that _worker is not provided with an older block
> Re-introduce re-registration test

- src/relayserver/RegistrationManager.ts
- src/relayserver/RelayServer.ts
- src/relayserver/ServerConfigParams.ts
- src/relayserver/StoredTransaction.ts
- src/relayserver/TransactionManager.ts
- src/relayserver/TxStoreManager.ts
- test/TxStoreManager.test.ts
- test/relayserver/RegistrationManager.test.ts
- test/relayserver/RelayServer.test.ts
- test/relayserver/RelayServerRequestsProfiling.test.ts
- test/relayserver/ServerTestUtils.ts
- test/relayserver/TransactionManager.test.ts
Date/time is an extremely unreliable measurement in terms of blockchain
and is hard to test for.
This PR makes TransactionManager remember the block height at the point
of the transaction creation.
Also:
1. Create StoredTransaction in place of StoredTx and StoredParams
2. Add 'pendingTransactionTimeoutBlocks', 'confirmationsNeeded',
'retryGasPriceFactor' and 'maxGasPrice' to the Server Config struct
3. Separate database cleanubp and gas price boost logic & test
4. 'resend multiple unconfirmed transactions' skipped and must be redone
> Use block count instead of timestamp as pending state timeout units

- dockers/jsrelay/Dockerfile
- dockers/relaydc/docker-compose.yml
- package.json
- src/relayclient/ContractInteractor.ts
- src/relayserver/RelayServer.ts
- test/relayclient/ContractInteractor.test.ts
updated versions to 2.0.0-beta.2
disabled beta version checking (so beta.2 relayer will work with existing deployed beta.1 hub)
(a separate issue is to fix our versioning check)
> relayer 2.0.0-beta.2

- contracts/forwarder/Forwarder.sol
- contracts/forwarder/IForwarder.sol
- contracts/forwarder/test/TestForwarder.sol
- src/cli/CommandsLogic.ts
- src/common/EIP712/ForwarderUtil.ts
- src/common/EIP712/TypedRequestData.ts
- src/common/Environments.ts
- test/Flows.test.ts
- test/Forwarder.test.ts
- test/PaymasterCommitment.test.ts
- test/RelayHub.test.ts
- test/RelayHubGasCalculations.test.ts
- test/RelayHubPenalizations.test.ts
- test/SampleRecipient.test.ts
- test/TestBatchForwarder.test.ts
- test/Utils.test.ts
- test/relayclient/KnownRelaysManager.test.ts
- test/relayclient/RelayClient.test.ts
- test/relayclient/RelayProvider.test.ts
- test/relayserver/RelayServer.test.ts
- test/relayserver/RelayServerRequestsProfiling.test.ts
- test/relayserver/ServerTestEnvironment.ts
- test/relayserver/TransactionManager.test.ts
Without it, requests from one forwarder can be replayed through another forwarder (on the same network, or on another network)
By registering the domainSeparator, the forwarder can verify it appears in it as the verifyingContract, and that the chainId is valid.
> OG-210 Forwarder add registerDomainSeparator

- src/common/dev/NetworkSimulatingProvider.ts
- src/common/dev/ProfilingProvider.ts
- src/common/dev/SendCallback.ts
- src/common/dev/WrapperProviderBase.ts
- src/relayclient/ContractInteractor.ts
- src/relayclient/GSNConfigurator.ts
- src/relayclient/RelayClient.ts
- src/relayserver/RegistrationManager.ts
- src/relayserver/RelayServer.ts
- src/relayserver/TransactionManager.ts
- test/Utils.test.ts
- test/dummies/BadContractInteractor.ts
- test/relayclient/ContractInteractor.test.ts
- test/relayclient/GSNConfigurator.test.ts
- test/relayclient/RelayClient.test.ts
- test/relayserver/NetworkSimultaion.test.ts
- test/relayserver/RegistrationManager.test.ts
- test/relayserver/RelayServer.test.ts
- test/relayserver/RelayServerRequestsProfiling.test.ts
- test/relayserver/ServerTestEnvironment.ts
- test/relayserver/ServerTestUtils.ts
- test/relayserver/TransactionManager.test.ts
- yarn.lock
As there is no way to broadcast a transaction with Web3, implement the
low-level RPC call directly in the ContractInteractor.
Also:
1. Introduce Web3Provider type definition
2. Extract common 'WrapperProviderBase' abstract class
3. Make 'pollNonce' always return locally known nonce
> OG-219 Make RelayServer not wait for the transaction to be mined

- src/relayclient/ContractInteractor.ts
- src/relayserver/RegistrationManager.ts
- test/TestUtils.ts
- test/relayserver/RegistrationManager.test.ts
- test/relayserver/RelayServerRequestsProfiling.test.ts
- test/relayserver/ServerTestEnvironment.ts
relayer should withdraw funds after only after unstakeDelay
* HubUnauthorized - should wait until the removalBlock event param
* StakeUnlocked - should wait until the withdrawBlock event param
withdrawing any funds from worker before that makes the relayer penalizeable...
> OG-187 withdraw too early

- src/cli/CommandsLogic.ts
- src/relayserver/RelayServer.ts
- src/relayserver/ServerConfigParams.ts
- src/relayserver/TransactionManager.ts
- truffle.js
- removed error messages during registration (which are not errors)
- it takes ~3 blocks to register relayer. increased "gsn
relayer-register" timeout to 60 seconds.
- moved some "info" to "debug"
- "null block in receipt" appears too often, and doesn't reflect an
error. now doesn't throw an exception - just log a line.
- polling interval reduced to 3sec
- ready state times-out after 3 `checkInterval` intervals, so any kind
of error will make the server "not ready" at most with 30 sec delay
(client has 10-sec timeout, so they will switch to other relayer faster)
> fix relayer registration flow.

- package.json
- src/relayclient/ContractInteractor.ts
- src/relayclient/LightTruffleContract.ts
- src/relayserver/RelayServer.ts
- test/relayclient/GSNConfigurator.test.ts
- test/relayserver/RelayServer.test.ts
- test/relayserver/RelayServerRequestsProfiling.test.ts
- yarn.lock
remove TruffleContract dependency
Use instead "light" version with has the same syntax ("at" function,
options as last arg, "intelligent" call/send method, getPastEvents with
"args") - as much as our project requires..
> OG-254 "Light" TruffleContract

- src/relayserver/RelayServer.ts
- src/relayserver/ServerConfigParams.ts
- test/relayserver/RegistrationManager.test.ts
- test/relayserver/RelayServer.test.ts
- relayer timeout now managed by setTimeout callback
- added deferReadiness: control when setReady takes effect immediately or after delay (see below): deferReadiness becomes "true" after first crash of worker.
- added timeToReady: when setting relayer to ready (in deferReadiness), it doesn't take effect immediately but only after readyTimeout.
- removed the "ready" flag. instead, there is "futureReadyTime":
- < Date.now() - we're already ready
- Nan - we're in "not-ready" state (after exception)
- &gt; Date.now() - we're waiting for this future time to become ready
- The "deferReadiness" controls whether setReadyState(true) will set
futureTime to "now" or to some time into the future
> OG-275 fix relayer state timeout

- src/relayclient/ContractInteractor.ts
- src/relayclient/RelayClient.ts
- test/dummies/BadContractInteractor.ts
- test/relayclient/RevertMessage.test.ts
Client should see revert reasons (when called as view functions), as
these often contains useful diagnostics (e.g. paymaster not funded)
Unfortunately, there is no standard of returning revert reasons, and
Parity revert reason is hidden by the underlying provider in generic
exception.
Geth revert reason can be parsed (as ganache...)
The new test (RevertMessage.test.ts) runs on ganache, but can also be
executed as stand-alone against rinkeby (geth) where it succeeds ,and
kova (parity) where it fails..
> OG-268: revert reason of relayCall

- src/common/EIP712/ForwarderUtil.ts
- src/relayclient/ContractInteractor.ts
- src/relayclient/GsnEvents.ts
- src/relayclient/RelayClient.ts
- src/relayclient/RelayProvider.ts
- src/relayserver/RelayServer.ts
- test/relayclient/ContractInteractor.test.ts
- test/relayclient/RelayClient.test.ts
default construction should be: await new RelayClient(...).init()
Can still construct the old way, but it will generate a warning (since
it delays the first transaction)
NOTE: init() is now guarded with mutex, since its possibel that
relayTransaction() will be called before original init() finished.
> OG-280 relayclient initialization outside of first transaction

- package.json
- src/relayclient/GSNConfigurator.ts
- src/relayclient/RelayClient.ts
- test/relayclient/RelayClient.test.ts
It is possible tot make relayed calls to contracts that are not
recipients if they do not accesss 'msg.sender'.
This flag enables such use-case.
> OG-293 Allow skipping 'isTrustedForwarder' check

- src/common/VersionsManager.ts
- src/relayclient/ContractInteractor.ts
- src/relayclient/GSNConfigurator.ts
- test/common/VersionManager.test.ts
By default, required version is current version with patch=0
that is, current 2.0.1 is satisifed with "2.0.0"
it is still possible to override this default using config param
requiredVersionRange (which should include the "^" marker)
> OG-227 required version logic

- src/relayclient/GSNConfigurator.ts
- src/relayclient/KnownRelaysManager.ts
- test/relayclient/KnownRelaysManager.test.ts
added configuration item `relayLookupWindowParts` (which defaults to
"1"), to split the lookup window (defined in blocks) to multiple
requests.
added a code to increase the lookupWindowParts in case the lookup
transaction fails on "query returned more than XXX events"
(note that the increase stays in memory. if the client reloads, it will
use the configured value again)
> OG-122: split lookup window

- src/relayclient/AccountManager.ts
- src/relayclient/RelayProvider.ts
- test/relayclient/AccountManager.test.ts
- test/relayclient/RelayProvider.test.ts
Remove option to add keypair with a buffer as I can't think of a usecase
where this is more convenient
> OG-79: Add account should accept hex string for private key

- src/relayserver/RelayServer.ts
The purpose of the random 'sleep' is to make it harder for attackers to
trick the relays into broadcasting the transaction that would otherwise
fail validation. If sleep is done after the broadcst, it has no effect.
> OG-234 Make 'sleep' for alerted mode be the first thing done

- src/relayserver/RelayServer.ts
- src/relayserver/ReputationEntry.ts
- src/relayserver/ReputationManager.ts
- src/relayserver/ReputationStoreManager.ts
- src/relayserver/runServer.ts
- test/relayserver/ReputationManager.test.ts
This will prevent the bug where paymaster reputation is permanently
affected by the same accepted/rejected event on every server restart.
This should also prevent crash on update to version >2.0.3 (OG-331)
> OG-349 Shortcut: disable storage for Reputation Manager (and OG-331)

- src/relayserver/RelayServer.ts
it doesn't give any info, and still emitted every 10 seconds,
only to make huge useless logs.
> Remove _shouldRegisterAgain log

- contracts/BaseRelayRecipient.sol
- contracts/RelayHub.sol
- contracts/StakeManager.sol
- contracts/interfaces/GsnTypes.sol
- contracts/interfaces/IRelayHub.sol
- contracts/interfaces/IStakeManager.sol
- migrations/2_deploy_contracts.js
- src/cli/CommandsLogic.ts
- src/common/Environments.ts
- test/Flows.test.ts
- test/PaymasterCommitment.test.ts
- test/RelayHub.test.ts
- test/RelayHubGasCalculations.test.ts
- test/RelayHubPenalizations.test.ts
- test/RelayHubRegistrationsManagement.test.ts
- test/SampleRecipient.test.ts
- test/StakeManager.test.ts
- test/TestBatchForwarder.test.ts
- test/common/ContractInteractor.test.ts
- test/relayclient/KnownRelaysManager.test.ts
- test/relayclient/RelayClient.test.ts
- test/relayclient/RelayProvider.test.ts
- test/relayclient/RelaySelectionManager.test.ts
- test/relayserver/ReputationFlow.test.ts
- test/relayserver/ServerTestEnvironment.ts
6.8-6.10 - add '@notice' comments to  GsnTypes about gas price, fees
6.12 - inconsistent natspec compliance in comments
6.20 - _msgSender only works on msg.data >= 24
6.28 - workerCount[relayManager] read thrice in this function
6.38 - the unstakeDelay could be accidentally set to unrealistically
long periods of time resulting in a forever locked stake
> OG-413 Minor audit issues

- contracts/forwarder/Forwarder.sol
- test/forwarder/Forwarder.test.ts
not sure why it doesn't work: there is a buffer gas for the post-execute transfer, but it fails to transfer.
> OG-410: forward value only if req value

- contracts/test/TestRecipient.sol
- package.json
- src/common/Utils.ts
- src/relayserver/RelayServer.ts
- test/Flows.test.ts
- test/RelayHubGasCalculations.test.ts
- test/TestUtils.ts
- test/relayclient/RelayClient.test.ts
1. Emit 'gasleft' in the TestRecipient to check it is close to requested
2. Set high target worker balance for large gas limit test
3. Take into account calldata cost when calculating external gas limit
(defaultEnvironment is hard-coded as of now)
4. Multiply gas limit by a factor to accomodate EIP-150 63/64th rule
(factor hardcoded at 1.1 as of now)
5. Increase 'run-with-testrpc' gas limit for large gaslimit test
> OG-427 Make Relay Server account for 63/64 rule estimating 'relayCall' gas limit

- packages/dev/src/GsnTestEnvironment.ts
- packages/dev/test/TestUtils.ts
- packages/relay/src/RegistrationManager.ts
- packages/relay/src/ServerConfigParams.ts
There is no need to pass Stake Manager address in a configuration as it
is read in 'init' from RelayHub anyways.
> Read Stake Manager address from ContractInteractor

- packages/common/src/ContractInteractor.ts
- packages/provider/src/GSNConfigurator.ts
- packages/provider/src/RelayClient.ts
Client crash on "invalid externaGasLimit" during request verification
root cause:
when making a view call, kotti can't pass more than (blockGasLimit/2)
gas. this breaks our calculation of externalGasLimit- initialGas.
Workaround: client to pass no more than blockGasLimit/3 during client
verification.
NOTE: a complete solution might be to copy the complete calculation of
maxPossibleGas from the relayer.
> OG-502 Kotti client crash on "invalid externalGasLimit"

- packages/provider/src/GSNConfigurator.ts
- packages/provider/src/KnownRelaysManager.ts
by default, we search for registration events (for specific relayers)
from block 1.
This works great no ethereum mainnet, testnets.
Some alternate networks (mumbai, kotti) are slower to handler such large
block ranges.
For such networks, the client should configure
relayRegistrationLookupBlocks, as registrations are only looked up in
that block range.
This value should be smaller than the server's registrationBlockRate,
which is the rate the relayers refresh their registration.
> OG-513 add client "registration lookup window"

- packages/cli/package.json
The `bin` field was missing in the `package.json` file.  This field allows npm to simlink correctly the binary file.
#642
> Add bin field in package.json file

- packages/cli/src/CommandsLogic.ts
- packages/common/src/ContractInteractor.ts
- packages/dev/test/RegistrationManager.test.ts
- packages/dev/test/ServerTestEnvironment.ts
- packages/relay/src/RegistrationManager.ts
Now server validates stake status with hub before trying to add
workers/register
> Fixing server registration

- packages/common/src/ContractInteractor.ts
- packages/common/src/types/GsnTransactionDetails.ts
- packages/dev/test/Flows.test.ts
- packages/dev/test/RelayServer.test.ts
- packages/dev/test/ServerTestEnvironment.ts
- packages/dev/test/common/StatisticsManager.test.ts
- packages/dev/test/penalizer/PenalizationFlow.test.ts
- packages/dev/test/provider/GsnTestEnvironment.test.ts
- packages/dev/test/provider/RelayClient.test.ts
- packages/provider/src/RelayClient.ts
- packages/provider/src/RelaySelectionManager.ts
This functionality basically only makes sense in tests and should not be
exposed to users.
A client app should initialize a RelayProvider for a specific
configuration to avoid compatibility issues.
Note that it also means that initialization of a ContractInteractor
without a paymaster address is no longer supported.
> OG-322 Remove ability to pass 'forwarder' and 'paymaster' addresses as tx details

- packages/paymasters/contracts/SingleRecipientPaymaster.sol
a paymaster for a single recipient contract.
- reject requests if destination is not the target contract.
- reject any request if the target contract reverts.
> SingleRecipientPaymaster

- dockers/relaydc/config-sample/gsn-relay-config.json
`ownerAddress` is a required field in the gsn-relay-config.json, but is
missing from the sample configuration file.
> add ownerAddress to sample server config

- packages/relay/src/RelayServer.ts
- packages/relay/src/TransactionManager.ts
apply our minimum value also to boosted transactions.
(NOTE: we still don't know how a small (e.g. 1 wei) value got into the
DB of old transactions, but in general, current GasPrice is good minimum
not only for new transactions but also for boosted transactions.
> OG-630 - Boosted gasPrice is sometimes lower after boosing than before

- .gitignore
- htpasswd
- package.json
- verdaccio/.verdaccio-db.json
- verdaccio/README.md
- verdaccio/verdaccio.yaml
- verdaccio/yarn
- verdaccio/yarnrc
verdaccio-start - (in separate terminal) start local npm repository
verdaccio-publish - like lerna-publish, BUT only to local verdaccio repo
(and no git-push)
gsn/verdaccio/yarn - wrapper for yarn, to use local repo: use from a
test app to install the just-published test version.
> dry-run publish support (using verdaccio)

- packages/cli/src/CommandsLogic.ts
- packages/common/src/ContractInteractor.ts
- packages/dev/test/RelayServer.test.ts
- packages/relay/src/RelayServer.ts
- packages/relay/src/TransactionManager.ts
perform gas estimation when doing value-transfer, instead of assuming
fixed-cost (which is different on rollups)
NOTE: should perform such estimates for other transactions, not only
value transfers.
> use estimateGas instead of fixed cost

- packages/contracts/package.json
- packages/paymasters/package.json
these are not used directly, so they only generate "warnings" when
installing the package.
> Port to master: Remove unused peerDependencies

- packages/dev/test/RegistrationManager.test.ts
- packages/relay/src/RegistrationManager.ts
- packages/relay/src/RelayServer.ts
- packages/relay/src/ServerConfigParams.ts
- packages/relay/src/TxStoreManager.ts
There is an inherent race condition between server sending a transaction
and observing the result in emitted event logs.
Up until now, the code considered the transaction to stop being
'pending' the moment it is mined. However, it appears to take more time
to get the RPC node to provide a satisfying response to
'getTransactionReceipt' and 'getPastEvents', causing the server to send
multiple identical transactions.
Make 'recentActionAvoidRepeatDistanceBlocks' a parameter
> OG-656: FOR MASTER: Consider a transaction 'pending' for N blocks after mining

- packages/provider/src/KnownRelaysManager.ts
- packages/provider/src/RelayClient.ts
Note: there is no way to prevent Metamask from logging an error. We do
the best-effort trying to fetch a transaction receipt first.
At least now it will try to inform people this error is not really an
error.
> OG-619: remove RelayProvider false errors.

- packages/relay/src/RelayServer.ts
when starting relayer, don't read back events. start from current (or
-10) blocks.
> OG-861-relayer-events

- packages/deployer/hardhat.config.ts
- packages/deployer/package.json
- packages/deployer/src/deployUtils.ts
- packages/deployer/src/exportTask.ts
- add fields exported network (title, explorer)
- remove obsolete config params (relayer fees)
- the generated exported network now looks like this (added description, explorer, symbol)
- 
```
{
"3": [
{
"description": "Ropsten",
"symbol": "ROP",
"explorer": "https://ropsten.etherscan.io",
"name": "ropsten",
"chainId": "3",
"contracts": {
...
```
> deployer fixes

- packages/cli/src/commands/gsn-paymaster-balance.ts
reported in https://github.com/opengsn/gsn/issues/835:
`gsn paymaster-balance` aborts on error:
```
TypeError: Cannot read property 'balanceOf' of undefined
```
missing init() for CommandsLogic()
> gsn paymaster-balance doesn't work.

- packages/contracts/src/test/TestGatewayForwarder.sol
- packages/dev/test/RelayHub.test.ts
As was correctly pointed out, the forwarder itself is not a production ready contract but is only a stub for tests and so the name should reflect that.
> OG- 957: Rename 'GatewayForwarder' to 'TestGatewayForwarder'

- packages/cli/src/commands/gsn-send-request.ts
- packages/dev/package.json
- packages/dev/test/provider/RelayProvider.test.ts
- packages/provider/src/RelayProvider.ts
This will raise an ignoreable TypeScript error in:
'new Web3(relayProvider)'
for Web3.js;
but it will solve a more common one:
'new Web3Provider(provider)'
for Ethers.js
> OG-1030: Make RelayProvider implement ExternalProvider interface

- packages/common/src/Utils.ts
- packages/dev/test/provider/RelayClient.test.ts
- packages/provider/src/RelaySelectionManager.ts
The "max priority fee per" gas after adjustment for a "Relay Ping Response" may exceed "max fee per gas" leading to a broken GSN client state.
> OG-1039: Fix "max priority fee per" exceeding "max fee per gas"
