opengsn/gsn

.circleci/config.yml
dock/Dockerfile
server/Makefile

server's makefile: added "go-get" just to get geth sources
cleaned up dockerfile
config to use the above.

Updated CI config, dockerfile, server makefile

---

contracts/RelayHub.sol
server/src/librelay/relay_server.go
src/js/relayclient/utils.js
test/relay_contract.js
test/server_helper_test.js
test/testutils.js

Fixing penalize flow issues after changing stake/register mechanism

Penalize flow

---

contracts/RelayHub.sol
test/relay_contract.js
test/testutils.js

Add parametrized test to check that relay's balance on RelayHub receives
an adequate compensation from Relay Recepient's stake.
Calculate gas overhaed of relayed transacion to be 47135 gas.

GLS-16 Compensate relays

---

restart-relay.sh
src/js/relayclient/ServerHelper.js
src/js/relayclient/relayclient.js
src/js/webtools/relaymanager.js
test/clientlib.js
test/testutils.js

- default to eth.gasPrice()*1.1
- if client request contains gas price, use that.
- RelayClient can have "force_gasPrice" to force a value (overrides
client setting)
- filter out relays with have MinGasPrice higher than request value.

Client gas price

---

src/js/relayclient/ServerHelper.js
src/js/relayclient/relayclient.js
test/server_helper_test.js

* add `gaspriceFactorPercent` - increase (in %) over current gasPrice
average
* added tests for `ActiveRelayPinger`

Client Gasprice - config, test

---

server/Makefile
server/src/RelayHttpServer.go
server/src/librelay/relay_server.go
server/src/librelay/tbk_ethclient.go
server/src/utils.go
src/js/relayclient/relayclient.js
test/clientlib.js
test/flows.js
test/server_helper_test.js
test/testutils.js

Need to better handles delays when testing

Gasprice periodic update

---

package.json
scripts/fundrelay.js
src/js/relayclient/relayclient.js
test/clientlib.js

fix gasLimit selection (force_gasLimit, then explicit gas_limit)

fix gasLimit

---

server/src/RelayHttpServer.go
server/src/librelay/relay_server.go

Also adding logs on failure in canRelay()

Fixing port parameter

---

.gitignore
src/js/relayclient/ServerHelper.js
src/js/relayclient/relayclient.js
src/js/webtools/relaymanager.js
truffle.js

Note: actual money is used in this network.
Mnemonic is git-ignored.

Add 'xDai POA Mainnet' support

---

package-lock.json
src/js/relayclient/ServerHelper.js
src/js/relayclient/relayclient.js
test/clientlib.js
test/flows.js

cleaned up error strings
`DEBUG=1 npm test` to enable library logging while running tests

Logging fixups

---

package-lock.json
package.json
scripts/gsn-dock-relay
scripts/gsn-dock-relay-ganache
scripts/gsn-stat.js

added gsn-stat - network statistics tool, for local/ropsten/xdai
launch with "npx gsn-stat" when our project is installed.
also moved docker launches to commands:
"npx gsn-dock-relay"
"npx gsn-dock-relay-ganache"
from within our project, they are in "./scripts" folder.

gsn-stat, other cmdline tools

---

contracts/GsnUtils.sol
contracts/RelayHub.sol
contracts/RelayHubApi.sol
contracts/RelayRecipient.sol
contracts/SampleRecipient.sol
src/js/relayclient/RelayClient.js
test/relay_client_test.js

1. Move 'checkSig' to the GsnUtils
2. Rename 'sig' to 'approval' in contracts code
3. Add 'approval' to the 'accept_relayed_call'
4. Implement a sample signature check in SampleRecipient

Initial implementation of the 'Dapp approval' mechanism

---

README.md

Added ./dock/run.sh npm install so that users can install docker dependencies.

Added ./dock/run.sh npm install

---

contracts/RelayHub.sol
server/src/librelay/relay_server.go
test/relay_hub_test.js

Fixing tests & comments

---

package-lock.json
server/src/.gitignore
src/js/relayclient/RelayClient.js
src/js/relayclient/ServerHelper.js
test/relay_client_test.js
test/server_helper_test.js

Client manage relay reputation

---

.eslintrc.js
contracts/IRelayHub.sol
contracts/RelayHub.sol
contracts/SampleRecipient.sol
package-lock.json
package.json
test/RelayHub.test.js
test/relay_hub_test.js

This PR fixes a bug where the recipient's balance is checked after `preRelayedCall` is called, meaning balance draining during that call is not detected. I also added new tests (in a separate test file - future PRs will also use this new test suite) to check for all scenarios.

Recipient balance check bugfix

---

package.json
yarn.lock

fix "high" vulnerability of lodash<4.17.13 (CVE-2019-10744)

fix lodash vulnerability.

---

contracts/RelayHub.sol
test/RelayHub.test.js
test/relay_hub_test.js

Prveiously we only compared tx.data.

Fixing penalizeRepeatedNonce to also consider gasLimit,value and destination

---

server/src/RelayHttpServer.go
server/src/librelay/relay_server.go
test/flows_test.js
test/relay_client_test.js

Fix server to look after Unstaked event before sending balance

---

scripts/fundrelay.js

use ```getRelay(relayaddr).totalStake``` instead of ```stakeOf``` function

fix fundrelay script

---

.gitignore
package.json
src/js/webtools/relaymanager.js
webtools.webpack.js
yarn.lock

use getRelay(relayaddr).totalStake, owner
instead of stakeOf, ownerOf function
also, make `yarn webtools` run out-of-the-box ...

fix webtools (relaymanager)

---

dock/run.sh
package.json
scripts/gsn-dock-relay
serverdock/package.json

client npm package
docker image (referenced from npm package)

0.4.0-beta2

---

server/src/librelay/relay_server.go

Relay server crashed during startup if the connection to the network was unavailable, since it loaded and cached the chain id on startup. This fixes that by loading (and caching) the chain ID lazily.
This is particularly useful for testing, since it does not require a local ganache to be running before starting the relay server.

Load chain ID lazily in relay server

---

.gitattributes
contracts/RelayHub.sol

expose current commit-id in relayhub

Add git commit-id to RelayHub

---

contracts/RelayHub.sol
server/Makefile
test/relay_hub_test.js

Also fixing bug in server Makefile.
This fixes issue addressed in PR #202

Fix recipient balance check

---

contracts/SampleRecipient.sol
server/src/librelay/relay_server_test.go

Adding another test to the gas cost calculation of the relayed encoded function.

Gas cost test

---

server/Makefile
server/src/librelay/relay_server.go

Adding clean target to Makefile

Adding approvalData to requiredGas calculation

---

server/src/librelay/relay_server.go
server/src/relay/RelayHttpServer.go

RegistrationBlockRate bugfix

---

dock/Dockerfile

Added dependencies of libusb-1.0-0 libudev-dev so that the dockerfile builds

update dockerfile to add dependencies

---

server/src/relay/RelayHttpServer.go

Fixes #241 by implementing the recommended changes to the keepAlive method

Fix for multi registration bug

---

server/Makefile

make -C server
should check and exit fast if the server is already built.

fix go makefile

---

buidler.config.js
contracts/paymaster/IUniswap.sol
contracts/paymaster/TokenGasCalculator.sol
contracts/paymaster/TokenPaymaster.sol
contracts/test/TestProxy.sol
contracts/test/TestUniswap.sol
package.json
test/TestUniswap.test.js
test/TokenPaymaster.test.js

Uniswap-based paymaster that pays gas with tokens of recipient contract.
(currently not cache-balanced, and charges the user too much: gasUsedBeforePost parameter of postRelayedCall is inaccurate)

TokenPaymaster

---

contracts/RelayHub.sol
contracts/interfaces/IRelayHub.sol
src/relayserver/RelayServer.js
src/relayserver/runServer.js
test/RelayServer.test.js
test/TestUtils.ts

So it is no longer needed when launching a RelayServer

API to expose stake manager from RelayHub

---

src/relayclient/RelayProvider.ts
test/relayclient/RelayProvider.test.ts

Now RelayProvider supports events (e.g. when wrapping a WebsocketProvider)

RelayProvider support events

---

helpers/gsn-balance.js
helpers/gsn-deploy-relay-hub.js
helpers/gsn-fund-paymaster.js
helpers/gsn-register-relayer.js
helpers/gsn-withdraw.js
helpers/src/deploy.js
helpers/src/helpers.js
helpers/src/register.js
src/relayserver/KeyManager.js
test/RelayServer.test.js

Also fixing bug in server: prefixing raw signedTx with 0x before sending it since geth throws ( while ganache not...)

Adding hd wallet provider for testnet support

---

helpers/gsn-deploy-relay-hub.js
helpers/gsn-run-relayer.js
helpers/gsn-stat.js
helpers/gsn.js
helpers/src/deploy.js
helpers/src/helpers.js
index.ts
jsrelay/.env
jsrelay/docker-compose.yml
package.json
scripts/prepublish
src/relayserver/RelayServer.js
src/relayserver/runServer.js
tsconfig.eslint.json
tsconfig.json

`gsn stat` for current network status
`gsn run-relayer` to start relay
- RelayHubAddress is mandatory.

cmdline fix

---

package.json
src/cli/CommandsLogic.ts
src/cli/commands/gsn-paymaster-fund.ts
src/cli/commands/gsn-relayer-register.ts
src/common/Utils.ts
src/relayclient/ContractInteractor.ts
src/relayclient/GSNConfigurator.ts
src/relayclient/GsnTestEnvironment.ts
src/relayclient/RelayClient.ts

OG-105 Remove OZ/TestHelpers from production dependencies

---

contracts/RelayHub.sol
contracts/interfaces/IRelayHub.sol
contracts/test/TestUtil.sol
contracts/utils/GsnEip712Library.sol
src/common/Environments.ts

This prevents truffle-flattener from working.

Fix circular dependency in solidity interfaces

---

contracts/RelayHub.sol
contracts/interfaces/IRelayHub.sol
contracts/test/TestRecipient.sol
src/common/Environments.ts
test/RelayHub.test.ts
test/RelayHubGasCalculations.test.ts
test/RelayServer.test.ts

emit revert reason in a separate transaction (TransactionResult), not in TransactionRelayed

OG135: Emit revert reason

---

package.json
src/cli/CommandsLogic.ts
src/cli/commands/gsn-deploy.ts
src/relayclient/GsnTestEnvironment.ts
test/Utils.test.ts
yarn.lock

1. Ask for confirmation before broadcasting transaction
2. Print transaction hash on each step
3. Allow all compontents of GSN to be passed as predeployed
4. Get gas price from ethereum node by default

OG-167 Improve RelayHub deployment script

---

contracts/BatchForwarder.sol
contracts/Penalizer.sol
contracts/RelayHub.sol
contracts/StakeManager.sol
contracts/forwarder/test/TestForwarderTarget.sol
contracts/interfaces/IRelayHub.sol
contracts/test/PayableWithEmit.sol
contracts/test/TestPaymasterEverythingAccepted.sol
contracts/test/TestPaymasterVariableGasLimits.sol
contracts/test/TestRecipient.sol
contracts/test/TestUtil.sol
contracts/utils/GsnEip712Library.sol
migrations/2_deploy_contracts.js
package.json
patches/truffle+5.1.26.patch
src/cli/CommandsLogic.ts
src/common/Environments.ts
src/relayclient/ContractInteractor.ts
src/relayclient/types/RelayHubConfiguration.ts
src/relayserver/RelayServer.ts
test/RelayHub.test.ts
test/RelayHubGasCalculations.test.ts
test/TestUtils.ts
test/Utils.test.ts
test/common/VersionManager.test.ts
test/relayclient/RelayProvider.test.ts

gsn//GreggJuanEduardoPH:master

---

contracts/test/TestPaymasterConfigurableMisbehavior.sol
src/relayclient/KnownRelaysManager.ts
src/relayclient/RelayClient.ts
src/relayserver/RelayServer.ts
src/relayserver/ServerConfigParams.ts
test/relayserver/RelayServer.test.ts
test/relayserver/ServerTestUtils.ts

 OG-152 Relay max exposure to paymaster acceptance budget 5b17108  post server refactor

---

src/cli/CommandsLogic.ts
src/cli/commands/gsn-status.ts
src/common/PingResponse.ts
src/relayclient/HttpClient.ts
src/relayclient/RelayClient.ts
src/relayclient/RelaySelectionManager.ts
src/relayserver/HttpServer.ts
src/relayserver/RelayServer.ts
test/TestUtils.ts
test/dummies/BadHttpClient.ts
test/relayclient/RelayClient.test.ts
test/relayclient/RelaySelectionManager.test.ts
test/relayserver/RelayServer.test.ts
test/relayserver/ServerTestEnvironment.ts

- client should pass paymaster to relayer when calling getaddr
- getaddr's maxAcceptanceBalance should be this paymaster (or default,
if given paymaster is not trusted)
- for this the relayer caches the gasLimits of each trusted relayer..

OG-237 acceptanceBalance protocol

---

src/relayclient/RelayProvider.ts

null response from provider is not an error - its just a null response

remove error message on "null" response

---

src/relayclient/KnownRelaysManager.ts
test/relayclient/KnownRelaysManager.test.ts
test/relayclient/RelayClient.test.ts

add a test to make sure preferred relays are used

OG-253 fix preferred relays

---

src/common/Utils.ts
src/relayserver/RelayServer.ts
src/relayserver/TransactionManager.ts
test/relayserver/NetworkSimultaion.test.ts
test/relayserver/ReputationManager.test.ts
test/relayserver/ServerTestEnvironment.ts
test/relayserver/TransactionManager.test.ts

Store the last boost block heigh, and use it if available to determine
transaction requires boosting.

OG-235 & OG-221: RelayServer improved boosting mechanism

---

src/relayserver/RelayServer.ts

relayer sends registerRelayServer tx over and over.

OG-338 relayers register repeatedly

---

contracts/BasePaymaster.sol

As I see the desired name is already applied

BasePolymaster: Remove outdated comment

---

src/common/ContractInteractor.ts

We could introduce a more advanced code to calculate external gas limit,
but for the purposes of the view function passing the worker balance if
it is lower then block gas limit sounds fine.

OG-334 Client choke on gas limit calculation on mainnet

---

dockers/cli/dbuild.sh
dockers/cli/webpack.config.js
dockers/jsrelay/dbuild.sh
dockers/jsrelay/webpack.config.js
dockers/relaydc/dbuild.sh
src/cli/commands/gsn.ts

use full version string of gsnRuntimeVersion, and in all docker images

OG-360 fix docker build scripts

---

src/common/ContractInteractor.ts
src/common/Version.ts
src/relayclient/GSNConfigurator.ts
src/relayclient/KnownRelaysManager.ts
src/relayclient/RelayClient.ts
src/relayserver/RelayServer.ts
src/relayserver/ServerConfigParams.ts
src/relayserver/penalizer/PenalizerService.ts
truffle.js

add explicit required version range (relevant when actual version
differs by more than patch version)

OG-361 remove: "beta ignore version compatibility"

---

src/common/ContractInteractor.ts

method should return gas limit, not cost (cost=gaslimit*gasprice)

OG-367 getMaxViewableGasLimit is broken

---

.circleci/config.yml
contracts/forwarder/Forwarder.sol
contracts/forwarder/IForwarder.sol
contracts/utils/GsnEip712Library.sol
scripts/download-solc
src/common/EIP712/ForwardRequest.ts
src/common/EIP712/TypedRequestData.ts
src/common/Environments.ts
src/common/types/RelayTransactionRequest.ts
src/relayclient/RelayClient.ts
src/relayserver/RelayServer.ts
src/relayserver/ServerConfigParams.ts
test/PaymasterCommitment.test.ts
test/RelayHub.test.ts
test/RelayHubGasCalculations.test.ts
test/RelayHubPenalizations.test.ts
test/TestBatchForwarder.test.ts
test/Utils.test.ts
test/common/ContractInteractor.test.ts
test/forwarder/Forwarder.test.ts
test/relayclient/AccountManager.test.ts
test/relayclient/RelayProvider.test.ts
test/relayserver/RelayServer.test.ts

initial fix
(note that fixing all GSN tests requires a "shortgun" change on all tests, to add the new param

OG-408 forwarder validUntil

---

contracts/forwarder/Forwarder.sol

should be just before actual call.

OG-421: fix forwarder gaslimit check

---

contracts/interfaces/GsnTypes.sol
test/RelayHubGasCalculations.test.ts

make sure that RelayData fields are ordered the same as the RELAYDATA_TYPE

OG-420: reorder RelayData fields

---

contracts/RelayHub.sol
contracts/interfaces/IRelayHub.sol
migrations/2_deploy_contracts.js
scripts/prepublish
src/cli/CommandsLogic.ts
src/common/Environments.ts
src/common/Utils.ts
src/common/types/RelayHubConfiguration.ts
src/relayserver/RelayServer.ts
test/RelayHub.test.ts
test/RelayHubGasCalculations.test.ts
test/RelayHubPenalizations.test.ts
test/TestBatchForwarder.test.ts
test/TestUtils.ts

calculate maxPossibleGas based on actual tx data cost (cost of putting the TX on-chain)
- since this value is based on externalGasLimit, make sure it is within  the valid range (each byte cost is 4..16)

OG-431: max possible gas tx data cost; OG-429 - put boundaries on externalGasLimit

---

dockers/relaydc/docker-compose.yml
lerna.json
package.json
packages/cli/README.md
packages/cli/package.json
packages/common/README.md
packages/common/package.json
packages/common/src/Version.ts
packages/contracts/README.md
packages/contracts/package.json
packages/contracts/src/BatchForwarder.sol
packages/contracts/src/Penalizer.sol
packages/contracts/src/RelayHub.sol
packages/contracts/src/StakeManager.sol
packages/contracts/src/forwarder/test/TestForwarderTarget.sol
packages/contracts/src/test/PayableWithEmit.sol
packages/contracts/src/test/TestPaymasterEverythingAccepted.sol
packages/contracts/src/test/TestPaymasterVariableGasLimits.sol
packages/contracts/src/test/TestRecipient.sol
packages/dev/README.md
packages/dev/package.json
packages/provider/README.md
packages/provider/package.json
packages/provider/src/GSNConfigurator.ts
packages/relay/README.md
packages/relay/package.json

on client, relayer, contracts.

update version to 2.2.0

---

packages/cli/src/utils.ts
packages/relay/src/runServer.ts

make sure relayer user the "requiredVersionRange" value read from
config file.

OG-474 - fix server config param requiredVersionRange

---

.gitignore
packages/cli/src/CommandsLogic.ts

don't use number/1e18 to display price in wei. use `fromWei`

OG-491 display gas price

---

packages/cli/package.json
packages/cli/src/GsnTestEnvironment.ts
packages/cli/src/commands/gsn-start.ts
packages/dev/package.json
packages/dev/src/index.ts
packages/dev/test/provider/GsnTestEnvironment.test.ts
packages/dev/test/provider/RevertMessage.test.ts
yarn.lock

fix circular dependency between "dev" and "cli" packages

OG-548 gsn-start

---

packages/contracts/.solhint.json
packages/contracts/src/BaseRelayRecipient.sol
packages/contracts/src/BatchForwarder.sol
packages/contracts/src/forwarder/test/TestForwarderTarget.sol
packages/contracts/src/interfaces/IRelayRecipient.sol
packages/contracts/src/test/TestRecipient.sol
packages/paymasters/contracts/PermitERC20UniswapV3Paymaster.sol
packages/paymasters/contracts/SampleRecipient.sol
packages/paymasters/contracts/deployproxy/ProxyIdentity.sol
packages/paymasters/contracts/helpers/SampleRecipient.sol
packages/paymasters/contracts/helpers/TestProxy.sol

- support solidity >=0.6
- relaxed license to MIT

Relax license, version of BaseRelayRecipient

---

packages/common/src/ContractInteractor.ts
packages/dev/test/ReputationFlow.test.ts
packages/dev/test/ReputationManager.test.ts
packages/paymasters/test/HashcashPaymaster.test.ts
packages/relay/src/ServerConfigParams.ts

Fixing getBlockNumber

---

packages/dev/test/TestUtils.ts
packages/dev/test/bls/BatchFlow.test.ts
packages/provider/src/bls/BatchRelayProvider.ts
packages/relay/src/BatchManager.ts
packages/relay/src/RelayServer.ts
packages/relay/src/ServerConfigParams.ts

support batch of multiple requests
(db sync issue if submitted multiple TXs too fast)

fix batch provider

---

packages/cli/src/CommandsLogic.ts
packages/cli/src/commands/gsn-relayer-withdraw.ts
packages/cli/src/utils.ts

Instead of only withdrawing from hub deposit.

Adding option to withdraw from manager eth account balance as well

---

dockers/prefixrouter/dbuild.sh
dockers/prefixrouter/prefixrouter

use default logging (which dumps X-Forwarder-For)

fix router logging

---

dockers/jsrelay/dbuild.sh
packages/cli/src/CommandsLogic.ts
packages/common/src/Utils.ts

allow "--stake 0.1"  as a valid input.

fix relayer-register

---

packages/dev/test/RelayServer.test.ts
packages/relay/src/RelayServer.ts

Include 'relayTransactionCalldataGasUsedCalculation' value when
comparing 'effectiveAcceptanceBudget' the relay is putting at risk
againts the 'maxAcceptanceBudget' config paramter.

OG-269 Relays vulnerable to attack through calldata gas

---

packages/paymasters/contracts/TokenPaymaster.sol
packages/paymasters/test/TokenPaymaster.test.ts

The error message of the require inside "_verifyPaymasterData" function should be updated to specifying V3 of Uniswap.

TokenPayMaster - update err msg

---

lerna.json
packages/cli/package.json
packages/common/package.json
packages/common/src/ContractInteractor.ts
packages/contracts/package.json
packages/deployer/package.json
packages/dev/package.json
packages/logger/package.json
packages/paymasters/package.json
packages/provider/package.json
packages/provider/src/RelayClient.ts
packages/relay/package.json

1. Take input gas price instead of re-querying fee history
2. Divide by RelayHub pctRelayFeeDev to avoid hitting false 'paymaster balance too low' error
3. Take 75% to leave some slack for base fee and calldata
4. Console.log what is going on there to simplify debugging

OG-1020: some issues in 'calculateDryRunCallGasLimit'

---

packages/provider/src/RelayProvider.ts

The 'Ethers.js' constructs its own "transaction receipt" object and loses the 'actualTransactionHash' value force-injected by the GSN.
Made 'getTransactionHashFromRequestId' more friendly to allow users to fetch receipt after transaction is mined.
For advanced users, cretated 'getPossibleTransactionHashFromRequestId' to allow users to observe the original transaction broadcast by the Relay Server.

OG-1063: Expose 'actual transaction hash' for users of Ethers.js
